---
- name: Install Caddy
  ansible.builtin.package:
    name: caddy
    state: latest
- name: Start Caddy service
  service:
    name: caddy
    state: started
    enabled: yes

- name: Print the encrypted variable
  debug:
    msg: "{{ secret }}"
  environment:
    - IPHUB_STREAM: "{{ myname }}"
