version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      # POSTGRES_DB: your_database_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_TIMEZONE: America/Curacao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    volumes:
      - pocketbase-data:/pb_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.pocketbase.rule=Host("pocketbase.localhost")
      - traefik.http.routers.pocketbase.entrypoints=web
      # - traefik.http.routers.pocketbase.middlewares=auth
      # - traefik.http.middlewares.auth.basicauth.users=${POCKETBASE_USERNAME}:${POCKETBASE_PASSWORD}

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
    restart: unless-stopped
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.smtp4dev.rule=Host("smtp4dev.localhost")
    #   - traefik.http.routers.smtp4dev.entrypoints=web
    # - traefik.http.routers.smtp4dev.middlewares=auth
    # - traefik.http.middlewares.auth.basicauth.users=${SMTP4DEV_USERNAME}:${SMTP4DEV_PASSWORD}

  traefik:
    image: traefik:v3.0
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - .traefik.yaml:/etc/traefik/traefik.yml:ro

    container_name: traefik
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.traefik.rule=Host("traefik.localhost")

networks:
  default:
    name: traefik
    external: true

volumes:
  pocketbase-data:
    driver: local
  postgres_data:
    driver: local
