version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      # POSTGRES_DB: your_database_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_TIMEZONE: America/Curacao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase-data:/pb_data
    ports:
      - "8090:8090"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
    restart: unless-stopped

# myproject/docker-compose.yml
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/html:ro

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - "5050:80"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile


networks:
  default:
    name: traefik
    external: true

volumes:
  pocketbase-data:
    driver: local
  postgres_data:
    driver: local
