api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  tcp:
    address: ":5432"

providers:
  docker: {}
  #file:
  #  filename: /dynamic.yml
  #  watch: true