
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    command: redis-server --requirepass {{ redis_password }}
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./data:/data
networks:
  default:
    name: local
    external: true

