---
- name: Setup Postgres directory
  ansible.builtin.file:
    path: ~/docker-compose/postgres
    state: directory

- name: Copy docker-compose.yaml to Postgres directory
  ansible.builtin.template:
    src: "templates/docker-compose-postgres.yaml"
    dest: "~/docker-compose/postgres/docker-compose.yaml"

- name: Run Postgres docker-compose up
  community.docker.docker_compose_v2:
    project_src: ~/docker-compose/postgres
    state: present

