---
- name: Setup Redis directory
  ansible.builtin.file:
    path: ~/docker-compose/redis
    state: directory

- name: Copy docker-compose.yaml to Redis directory
  ansible.builtin.template:
    src: "templates/docker-compose-redis.yaml"
    dest: "~/docker-compose/redis/docker-compose.yaml"

- name: Run Redis docker-compose up
  community.docker.docker_compose_v2:
    project_src: ~/docker-compose/redis
    state: present

