
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: semaphore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {{ postgres_password }}
      POSTGRES_TIMEZONE: America/Curacao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
networks:
  default:
    name: local
    external: true

volumes:
  postgres_data:
    driver: local
