---
- hosts: digital
  become: true
  vars_files: 
    - playbooks/vault.yml
  tasks:
    - name: Install Caddy
      ansible.builtin.package:
        name: caddy
        state: latest
    - name: Start Caddy service
      service:
        name: caddy
        state: started
        enabled: yes
