---
- hosts: digital
  become: true
  tasks:
    - name: Install Caddy
      ansible.builtin.package:
        name: caddy
        state: latest
    - name: Start Caddy service
      service:
        name: caddy
        state: started
        enabled: yes

    - name: Print the encrypted variable
      debug:
        msg: "{{ secret }}"

    - name: Set environment variable
      environment:
        IPHUB_STREAM: {{ IPHUB_STREAM }}
      # shell: my_command