---
- hosts: digital
  become: true
  tasks:
    - name: Remove Caddy
      ansible.builtin.package:
        name: caddy
        state: absent
    
    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    - name: Remove Docker
      ansible.builtin.package:
        name: apt-transport-https,ca-certificates,curl,software-properties-common,docker-ce
        state: absent


    - name: Delete Docker directory
      file:
        path: /var/lib/docker
        state: absent

